import { Poppins } from "next/font/google";
import "./globals.css";
import Layoutwrapper from "@/components/Layout/Layoutwrapper";
import { Toaster  } from "react-hot-toast";
import StickyOfferButton from "@/components/socialicons/stickybutton";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], 
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >

      <body className="h-full font-sans">
      <Toaster position="top-center top-20" autoClose={3000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss draggable pauseOnHover theme="light" />


        <Layoutwrapper>

<StickyOfferButton></StickyOfferButton>
          {children}
        </Layoutwrapper>  
      </body>
    </html>
  );
}